# -*- coding: utf-8 -*-
"""zoo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1obIaMAmTwhlrvQq1JmMwZuggDF8-7TCw
"""

def hours():
    print('Open 9-5 daily')

